capacityImageName = "capacityNow"
entitySelectedImageName = "entitySelected"
entityViewListImageName = "entityViewListImage"
fullScreenImageName = "fullScreen"
leavingStationImageName = "leavingStation"